default_language_version:
  python: python3

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit.git
    # Ruff version.
    rev: v0.1.5
    hooks:
      - id: ruff
        args:
          - --config=pyproject.toml
      - id: ruff-format
        args:
          - --config=pyproject.toml

  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.5.0
    hooks:
      # list of supported hooks: https://pre-commit.com/hooks.html
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-yaml
        args:
          - --allow-multiple-documents
      - id: debug-statements
      - id: detect-private-key
      - id: check-executables-have-shebangs
      - id: check-toml
      - id: check-case-conflict
      - id: check-added-large-files

  # md formatting
  - repo: https://github.com/executablebooks/mdformat.git
    rev: 0.7.17
    hooks:
      - id: mdformat
        args: ["--number"]
        additional_dependencies:
          - mdformat-gfm
          - mdformat-tables
          - mdformat_frontmatter

  # jupyter notebook cell output clearing
  - repo: https://github.com/kynan/nbstripout.git
    rev: 0.6.1
    hooks:
      - id: nbstripout

  # jupyter notebook linting
  - repo: https://github.com/nbQA-dev/nbQA.git
    rev: 1.7.0
    hooks:
      - id: nbqa-ruff
        args:
          - --config=pyproject.toml
          - --ignore=F811,F821,D417

  # - repo: local
  #   hooks:
  #     - id: pytest
  #       name: Run pytest
  #       # entry: pytest -vv
  #       entry: bash -c 'if [[ -z "${GITHUB_ACTIONS}" ]]; then pytest -vv; fi'
  #       language: system
  #       types: [python]
  #       pass_filenames: false
  #       always_run: true
